### ISSUE TITLE
Problema com SSL

### ISSUE THREAD

**Issue by diogotoscano** [deividfortuna/fipe#1]
Dependendo do servidor onde estiver rodando, precisa desabilitar a checagem do sertificado SSL com a opção CURLOPT_SSL_VERIFYPEER => 0 do curl.
É bom tambem checar o codigo de erro, mudei a função request para:

    private static function request($uri){
		
        try {
            $ch = curl_init($uri);
            $options = array(
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_FOLLOWLOCATION => 1,
                CURLOPT_TIMEOUT => 5,
                CURLOPT_CONNECTTIMEOUT => 5,
                CURLOPT_SSL_VERIFYPEER => 0,
            );
            curl_setopt_array($ch, $options);
            $html = curl_exec($ch);
			$httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);

            return ($httpcode>=200 && $httpcode<300) ? json_decode($html) : false;
			
        } catch(\Exception $e) {
            return false;
        }
    }

**Comment by deividfortuna** [comment]
Boa @diogotoscano, muito obrigado!
