### ISSUE TITLE
Listagem de modelos e anos

### ISSUE THREAD

**Issue by FredericoSFerreira** [deividfortuna/fipe#14]
Em algumas situações na listagem dos modelos ou anos o primeiro registro a ser retornado é **32000**
no propio exemplo da documentação  **32000** e o primeiro ano a ser retornado.
Exemplo:

https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas/59/modelos/5940/anos
`Array [6]
0: Object
nome: "32000 Diesel"
codigo: "32000-3"
1: Object
nome: "2016 Diesel"
codigo: "2016-3"
2: Object
nome: "2015 Diesel"
codigo: "2015-3"
3: Object
nome: "2014 Diesel"
codigo: "2014-3"
4: Object
nome: "2013 Diesel"
codigo: "2013-3"
5: Object
nome: "2012 Diesel"
codigo: "2012-3"`

Objeto 0 nome e **32000** por qual motivo este e o primeiro ano?

**Comment by deividfortuna** [comment]
Olá @FredericoSFerreira 

Da uma olhada no Issue #4
Espero ter ajudado. Abraço
