### ISSUE TITLE
Error 404 na Consulta

### ISSUE THREAD

**Issue by felipepalma14** [deividfortuna/fipe#15]
Estou tentando acessar a API e está retornando este erro. Para alguns modelo funciona normal.

![image](https://cloud.githubusercontent.com/assets/8844475/21658777/46b1c0c0-d29e-11e6-885e-d37c58e4443f.png)

Att.

**Comment by deividfortuna** [comment]
Olá @felipepalma14 
Houve um problema mas já foi normalizado. Obrigado por avisar :+1:

**Comment by felipepalma14** [comment]
Obrigado.
