### ISSUE TITLE
Erro js e php

### ISSUE THREAD

**Issue by juliopre** [deividfortuna/fipe#17]
Olá,
1 coisas estão acontecendo e gostaria de sua ajuda. A primeira é que quando eu tento fazer uma busca via jquery/ajax, o campo ano não exibe nenhum resultado, já os campos marca e modelo funcionam perfeitamente. Segue o código:

`var _urlacessoAPIFipe = 'https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas'; 

	// Resultados.
	$.getJSON(_urlacessoAPIFipe, function(data){
	  for (var i=0; i < data.length; i++){
	    $("#avaliar-marcas").append('<option value="' + data[i].codigo + '">' + data[i].nome + '</option>');
	  }
	  console.log("Quantidade de registros localizados: " + data.length);
	});

	//Selecione uma Marca
	$("#avaliar-marcas").change(function(){
		var marca = $("#avaliar-marcas").val();
		$("#avaliar-modelos").html('');
		$.getJSON('https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas/' + marca + '/modelos', function(data){
		  for (var i=0; i < data.modelos.length; i++){
		    $("#avaliar-modelos").append('<option value="' + data.modelos[i].codigo + '">' + data.modelos[i].nome + '</option>');
		  }
		  console.log("Quantidade de registros localizados: " + data.modelos.length);
		});
	});

	//Selecione um ano
	$("#avaliar-modelos").change(function(){
		var marca = $("#avaliar-marcas").val();
		var ano = $("#avaliar-modelos").val();
		$("#avaliar-ano").html('');
		$.getJSON('https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas/' + marca + '/modelos/' + ano + '/anos', function(data){
		  for (var i=0; i < data.ano.length; i++){
		    $("#avaliar-modelos").append('<option value="' + data.ano[i].codigo + '">' + data.ano[i].nome + '</option>');
		  }
		  console.log("Quantidade de registros localizados: " + data.ano.length);
		});
	});	`

A segunda. Estou utilizando o wordpress e quando eu importo o projeto pra dentro do meu servidor, aparece o seguinte erro
 Warning: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in ...../fipe/IFipe.php on line 30.

Sua API é muito bacana, e parabéns pelo trabalho

**Comment by juliopre** [comment]
Olá, eu acabei mandando o código anterior, vou atualizar apenas a parte do ano, onde deveria exibir o ano
`//Selecione um ano
	$("#avaliar-modelos").change(function(){
		var marca = $("#avaliar-marcas").val();
		var modelo = $("#avaliar-modelos").val();
		//document.write(marca+'<br>');
		//document.write(modelo);
		$("#avaliar-ano").html('');
		$.getJSON('https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas/'+ marca +'/modelos/' + modelo + '/anos', function(data){
		  for (var i=0; i < data.ano.length; i++){
		    $("#avaliar-ano").append('<option value="' + data.ano[i].codigo + '">' + data.ano[i].nome + '</option>');
		  }
		  console.log("Quantidade de registros localizados: " + data.ano.length);
		});
	});	`

EU coloquei document.write para verificar os códigos que estão sendo exibidos e estão corretos.

**Comment by deividfortuna** [comment]
Olá @juliopre, dei uma olhada aqui e econtrei um problema no seu javascript. Segue a código corrigido

```
var _urlacessoAPIFipe = 'https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas';
// Resultados.
$.getJSON(_urlacessoAPIFipe, function (data) {
    for (var i = 0; i < data.length; i++) {
        $("#avaliar-marcas").append('<option value="' + data[i].codigo + '">' + data[i].nome + '</option>');
    }
    console.log("Quantidade de registros localizados: " + data.length);
});

//Selecione uma Marca
$("#avaliar-marcas").change(function () {
    var marca = $("#avaliar-marcas").val();
    $("#avaliar-modelos").html('');
    $.getJSON('https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas/' + marca + '/modelos', function (data) {
        for (var i = 0; i < data.modelos.length; i++) {
            $("#avaliar-modelos").append('<option value="' + data.modelos[i].codigo + '">' + data.modelos[i].nome + '</option>');
        }
        console.log("Quantidade de registros localizados: " + data.modelos.length);
    });
});

//Selecione um ano 
$("#avaliar-modelos").change(function () {
    var marca = $("#avaliar-marcas").val(); var modelo = $("#avaliar-modelos").val();
    //document.write(marca+'<br>'); 
    //document.write(modelo);
    $("#avaliar-ano").html('');
    $.getJSON('https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas/' + marca + '/modelos/' + modelo + '/anos', function (data) {
        for (var i = 0; i < data.length; i++) {
            $("#avaliar-ano").append('<option value="' + data[i].codigo + '">' + data[i].nome + '</option>');
        }
        console.log("Quantidade de registros localizados: " + data.length);
    });
});
```

O problema estava na hora de tratar o resultado na ultima parte 

> //Selecione um ano


Em relação ao wordpress, não trabalho com wordpress acho que a biblioteca não é compativel :disappointed: 

Abraço.

**Comment by juliopre** [comment]
Muito Obrigado @deividfortuna.

Em relação ao wordpress, vou estudar um pouco mais e se caso eu conseguir avançar te aviso para que possa dar essa possibilidade aos usuários que usam a API.

Flw
