### ISSUE TITLE
Link offline - consulta

### ISSUE THREAD

**Issue by peteraf** [deividfortuna/fipe#19]
Olá alguns links estão offline, como exemplo abaixo:

https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas/59/modelos/5586/anos

Referente a : nome":"AMAROK CD2.0 16V\/S CD2.0 16V TDI 4x4 Die","codigo":5586}

Poderia conferir? Obrigado

**Comment by deividfortuna** [comment]
@peteraf resolvido.

Muito obrigado por reportar como sempre :+1:  
Grande abraço!
