### ISSUE TITLE
Consultar valores antigos

### ISSUE THREAD

**Issue by eduardoHoefel** [deividfortuna/fipe#20]
Gostaria de poder buscar o preço da tabela em outros meses/anos também, para saber o valor de depreciação do modelo. Teria como adicionar esta função?

**Comment by deividfortuna** [comment]
olá @eduardoHoefel, ainda não é possível, mas espero ter tempo para trabalhar nisso em breve.

obrigado.

**Comment by mscampos92** [comment]
esbarrei no mesmo desafio, consultar a tabela fipe com referencia diferente do mês atual, seria uma feature maravilhosa!!

**Comment by yancorrea1995** [comment]
@deividfortuna tem como habilitar para passarmos o código do mês de referencia como parâmetro na busca de valor? Na API ele pega a última tabela de referência (por exemplo 251), mas eu gostaria de passar como parâmetro esse codigo, pode ser opcional, assim não quebra a API pra quem já usa. Valeu, abraço!

**Comment by MarksEliel** [comment]
> olá @eduardoHoefel, ainda não é possível, mas espero ter tempo para trabalhar nisso em breve.
> 
> obrigado.

alguma novidade referente a isso?

**Comment by deividfortuna** [comment]
Opa galera acabei me envolvendo com outros projetos e esqueci dessa feature, mas tive um tempo livre e implementei hoje a API. Infelizmente nao tive tempo para atualizar a library mas se voces cosumem a API diretamente acho que vai solucionar o problema.

Agora voce pode passar um query parameter `reference` com o codigo da tabela de referencia na hora de consultar os precos. 

https://parallelum.com.br/fipe/api/v1/references
```json
[
{
"codigo": 273,
"mes": "agosto/2021 "
},
{
"codigo": 272,
"mes": "julho/2021 "
},
...
]
```

https://parallelum.com.br/fipe/api/v1/carros/marcas/59/modelos/5940/anos/2014-3?reference=271
```json
{
"Valor": "R$ 102.451,00",
"Marca": "VW - VolksWagen",
"Modelo": "AMAROK High.CD 2.0 16V TDI 4x4 Dies. Aut",
"AnoModelo": 2014,
"Combustivel": "Diesel",
"CodigoFipe": "005340-6",
"MesReferencia": "junho de 2021 ",
"TipoVeiculo": 1,
"SiglaCombustivel": "D"
}
```

https://parallelum.com.br/fipe/api/v1/carros/marcas/59/modelos/5940/anos/2014-3
```json
{
"Valor": "R$ 109.888,00",
"Marca": "VW - VolksWagen",
"Modelo": "AMAROK High.CD 2.0 16V TDI 4x4 Dies. Aut",
"AnoModelo": 2014,
"Combustivel": "Diesel",
"CodigoFipe": "005340-6",
"MesReferencia": "agosto de 2021 ",
"TipoVeiculo": 1,
"SiglaCombustivel": "D"
}
```

Abraco, no aguardo do seu feedback

**Comment by MarksEliel** [comment]
Dessa forma a gente consegue obter por exemplo:

Toyota > Etios:
Lista de Anos disponíveis?

Ou

Toyota > Ano:
Lista de Modelos disponíveis?

**Comment by deividfortuna** [comment]
@MarksEliel estamos discutindo isso na issue #50
