### ISSUE TITLE
Valores de referência

### ISSUE THREAD

**Issue by diegomamorim** [deividfortuna/fipe#21]
Olá Deivid, parabéns pela Api, muito legal. Eu consultei ela aqui e funcionou certinho, porém os valores de referência da Fipe que vieram nos resultados foram os de maio/2017. Como que é feita essa atualização na API para já vir os valores de junho/2017. 

Abraços

**Comment by deividfortuna** [comment]
Atualizado! Desculpa pela demora.

Abraço.

**Comment by diegomamorim** [comment]
Obrigado Deivid, Abraços
