### ISSUE TITLE
Consulta de modelos por ano

### ISSUE THREAD

**Issue by thalesreis** [deividfortuna/fipe#22]
Gostaria de saber se é possível ter o mesmo comportamento que a FIPE tem no site, onde é possível escolher uma marca e filtrar os carros pelo ano, antes de selecionar um modelo.

Eu reparei que existe o retorno dos modelos também retorna os anos. Dá para aproveitar essa informação?

**Comment by deividfortuna** [comment]
Ainda não é possível, mas pretendo estar implementando em breve como comentei no issue #20 

Vou fechar pois esta duplicado. Grande abraço.
