### ISSUE TITLE
API principal open source?

### ISSUE THREAD

**Issue by bazaglia** [deividfortuna/fipe#23]
Oi Deivid,

A API que essa biblioteca usa foi construída por você também, certo? Ela é um crawler que consulta o site da FIPE? Como pra aplicação que estou desenvolvendo preciso assumir o gerenciamento do hosting da API, estou interessado na API pura. Inclusive a aplicação é em node.js, posso desenvolver uma lib que consulta a API em node.js e compartilhá-la.

Pensei em te perguntar se não passou pela sua cabeça tornar o projeto inteiro open source, não só a biblioteca. Eu mesmo contribuiria pra ele se fosse o caso, pode ter certeza. 😄

**Comment by deividfortuna** [comment]
@bazaglia A da FIPE ainda não tenho interesse em tornar o código open source. A molicar não é de seu interesse? Acabei de publicar o código em nodejs.

Da uma olhada e me diz o que acha: https://github.com/deividfortuna/molicar

Grande abraço.
