### ISSUE TITLE
Serviço indisponível?

### ISSUE THREAD

**Issue by bruno-rodrigues** [deividfortuna/fipe#24]
A api está retornando 503. Está ciente disso @deividfortuna?

**Comment by deividfortuna** [comment]
hey @bruno-rodrigues, 
infelizmente estou, a Red Hat desligou o serviço gratuito onde a API estava hospedada.

Recebi esse email:
`Valued OpenShift Online user,This is your final notice that the sunset of the previous generationOpenShift Online 2 platform will be September 30, 2017. After tomorrow, applications created in Free and Bronze accounts in Red Hat OpenShift Online 2 will no longer be available.`

Estou a procura de novo servidores gratuitos que incluam: PHP, MySql e não necessariamente Nodejs, tem umas coisas em node mas posso reescrever em PHP.

Espero colocar o servidor no ar em breve

**Comment by felipepalma14** [comment]
Cara, ainda OFF, deixa funcionando até eu apresentar meu TCC, eheeh 
Qualquer coisa, estou por ai

**Comment by bruno-rodrigues** [comment]
Ainda não fiz a alteração na minha codebase, mas penso em tentar [isso](http://wipsites.com.br/servicos/api-fipe) enquanto o serviço do David estiver offline.

**Comment by deividfortuna** [comment]
@bruno-rodrigues essa API que você indicou parece não estar funcionando também. Utilizava a minha? :see_no_evil:

**Comment by bruno-rodrigues** [comment]
não testei ainda @davidfortuna, mas é muito possível que usava =)
Quais são os requisitos para sua API voltar ao ar?

**Comment by deividfortuna** [comment]
@bruno-rodrigues um servidor com PHP, Mysql, e SSL. Nesse final de semana estarei olhando para isso com mais atenção.

**Comment by felipepalma14** [comment]
Amém , preciso disto pra formar kk

**Comment by deividfortuna** [comment]
@bruno-rodrigues  @felipepalma14 acabei de subir em um servidor na AWS.

**Comment by felipepalma14** [comment]
@deividfortuna já está disponivel?

é o mesmo link: https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas ?

**Comment by rnrodrigues** [comment]
@felipepalma14 esse é o link: [https://fipe.parallelum.com.br/api/v1/carros/marcas](https://fipe.parallelum.com.br/api/v1/carros/marcas)
