### ISSUE TITLE
Erro: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by portalpesq** [deividfortuna/fipe#25]
Amigão, bom dia

estou tentando conectar ao novo link mas obtenho a seguinte a mensagem de erro nas minhas aplicações ( tentei pelo postman e também obtive a mesma mensagem de erro):

**Failed to load http://fipe.epizy.com/api/v1/motos/marcas/77/modelos/6408/anos: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://hmlg.55solucoes.com:81' is therefore not allowed access.**

**Comment by deividfortuna** [comment]
@portalpesq corrigindo apos mover a API para o AWS
