### ISSUE TITLE
Api fora do ar

### ISSUE THREAD

**Issue by pdias94** [deividfortuna/fipe#28]
Deivid, esta biblioteca é excelente... Porém está me dando retorno vazio 
Ocorreu algo? Segue o print do erro

![image](https://user-images.githubusercontent.com/30354593/32471371-0ecd86fc-c344-11e7-84d3-a944bf551a5c.png)

obs.: chamei o método Getmarcas

**Comment by ptsilva** [comment]
Veja a atualização no readme.
