### ISSUE TITLE
API FIPE não atualiza

### ISSUE THREAD

**Issue by VitorManoelDaSilvaPedro** [deividfortuna/fipe#29]
Olá Deivid, a API não está atualizando para Novembro,  e meu sistema está usando esta API como base. Teria como verificar para mim? Para atualizar sempre no dia 1? Valeu!

**Comment by thiagomdo1** [comment]
Atualiziou, mas agora está parada em janeiro de 2018...

**Comment by deividfortuna** [comment]
@VitorManoelDaSilvaPedro @thiagomdo1 está atualizada para o mês de Fevereiro 2018 :sunglasses:

**Comment by deividfortuna** [comment]
Vou deixar aberto para trabalhar em uma solução automatizada.

**Comment by thiagomdo1** [comment]
Valeu!

**Comment by deividfortuna** [comment]
@thiagomdo1 E ai, lancei uma nova versão da API e com essa nova versão esses problemas não devem ocorrer novamente 😎
