### ISSUE TITLE
Consulta com filtros por marca e modelo. 

### ISSUE THREAD

**Issue by xandedj** [deividfortuna/fipe#32]
Boa Tarde Amigo.

Desde já gostaria de parabenizá-lo pela iniciativa, e gostaria de sugerir que colocasse em algum desses serviços um filtro por marca e outro por modelo.

Desde já agradeço.

Alexandre Ramos - Abraços

**Comment by deividfortuna** [comment]
E ai @xandedj beleza?
Obrigado amigo! Já comecei a trabalhar nessa função mas ainda não tive tempo o bastante para finalizar espero terminar em breve. Assim que eu tiver algo mais real deixo informações aqui.

Grande abraço!
