### ISSUE TITLE
Requisição cors-origin bloqueada

### ISSUE THREAD

**Issue by adrianosilvavianna** [deividfortuna/fipe#33]
Olá amigos, 

Não tenho certeza, mas acredito que sou eu que esteja errando algo ao tentar buscar os dados de MODELOS na api de vocês. 

Tento fazer uma requisição Ajax simples

$.getJSON("https://fipe.parallelum.com.br/api/v1/carros/marcas/"+marca+"/modelos", function(data) {
                    console.log( data );
                })

e apresenta o seguinte erro : 

Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em https://fipe.parallelum.com.br/api/v1/carros/marcas/4/modelos. (Motivo: a pré-conexão CORS falhou).

será que eu estou fazendo a requisição da maneira errada ou algo na API ?

Obrigado!!

**Comment by deividfortuna** [comment]
Ola @adrianosilvavianna,
Isso é uma proteção dos navegadores modernos. Requisições Ajax para uma URL diferente que você está são bloqueadas por segurança.

Da uma olhada nesse artigo pode te ajudar: https://imasters.com.br/front-end/javascript/cross-origin-ajax-com-cors/?trace=1519021197&source=single

Grande abraço!

**Comment by adrianosilvavianna** [comment]
Obrigado!!

Mas o caso aconteceu pela forma com que chamava a requisição. 
Usei a biblioteca XMLHttpRequest e funcionou.

Exemplo de chamada com essa biblioteca está no link:

https://codepen.io/garethredfern/pen/yeqGMy?q=xmlhttprequest&limit=all&type=type-pens

Abraço!!
