### ISSUE TITLE
Combustível Só retorna Gasolina

### ISSUE THREAD

**Issue by MarcosEllys** [deividfortuna/fipe#34]
Menos nos modelos Flex o único combustível retornado é a gasolina

segue consulta realizada

https://fipe.parallelum.com.br/api/v1/carros/marcas/21/modelos/4763/anos/2013-1

**Comment by deividfortuna** [comment]
Opa @MarcosEllys, e ai cara beleza?

Então esse é um problema da FIPE mesmo. Ela só mostra o combustível principal que nesse caso é a gasolina. É possível ver na descrição do veículo que se trata de um flex mas o combustível vai sempre vir gasolina.
Não há nada que eu possa fazer. Se você consultar no site deles pode verificar que são as mesma informações.

Grande abraço.
