### ISSUE TITLE
API Fora do Ar

### ISSUE THREAD

**Issue by alansystem** [deividfortuna/fipe#35]
Tem previsão de volta?

**Comment by deividfortuna** [comment]
Olá,
Houve um numero anormal de requisições que acabou esgotando meu plano. Estou trabalhando para que esse problema não volte a ocorrer.

Provavelmente estará de volta na semana que vem, pois vou ter mais tempo para me dedicar durante o final de semana.
Grande abraço.

**Comment by deividfortuna** [comment]
problema foi resolvido mas precisei mudar a URL. A nova base é https://parallelum.com.br/fipe/api/v1

A antiga continua funcionando mas sem SSL.
