### ISSUE TITLE
Erro na api, page not found

### ISSUE THREAD

**Issue by victorstsw** [deividfortuna/fipe#36]
Erro na api, page not found, sem acesso!

**Comment by deividfortuna** [comment]
Olá,
Houve um numero anormal de requisições que acabou esgotando meu plano. Estou trabalhando para que esse problema não volte a ocorrer.

Assim que a API estiver de voltar aviso aqui.
Grande abraço.

**Comment by victorstsw** [comment]
Olá, vc usa uma hospedagem pra esse fim? eu posso colaborar pra manter a api 100% funcional! 
Em Sex, Mar 23, 2018 às 09:50, Deivid Fortuna  escreveu: Olá,
 Houve um numero anormal de requisições que acabou esgotando meu plano. Estou trabalhando para que esse problema não volte a ocorrer.
 Assim que a API estiver de voltar aviso aqui.
 Grande abraço.

**Comment by victorstsw** [comment]
Estou trabalhando em uma api própria da fipe! vou disponibilizar ela sem cota de trafego! vou disponibililar no meu git! Obrigado!

**Comment by marcelo-ribeiro** [comment]
Olá, amigo. Coloquei a chamada pra API com (http://) mas ainda assim continua indisponível.

**Comment by deividfortuna** [comment]
@marcelo-ribeiro eu tive mudar de servidor, então pode ser que o dns não esteja replicado na sua maquina. Confere ai e me avisa.

Se quiseres conferir como renovar o dns na sua maquina: http://kb.br.bluehost.com/limpando-o-cache-de-dns-do-seu-computador/

:sunglasses:

**Comment by marcelo-ribeiro** [comment]
@deividfortuna fiz o procedimento e continua indisponível.
![captura de tela 2018-03-26 as 14 58 14](https://user-images.githubusercontent.com/8428129/37923722-3d11ba76-3106-11e8-8dc2-390a0ad0003b.png)

**Comment by deividfortuna** [comment]
@marcelo-ribeiro Ahh, isso acontence porque você está tentando fazer um request http em um endereço https :sob: 

No seu caso o https teria que estar funcionando também.

**Comment by marcelo-ribeiro** [comment]
Entendi, mas no https não está funcionando :(

**Comment by deividfortuna** [comment]
@marcelo-ribeiro problema do ssl foi resolvido mas precisei mudar a URL. A nova base é `https://parallelum.com.br/fipe/api/v1`

**Comment by victorstsw** [comment]
@deividfortuna Mutio top David, parabéns, como posso retribuir?
