### ISSUE TITLE
Como faço para conseguir um Token??

### ISSUE THREAD

**Issue by gabrielrosas** [deividfortuna/fipe#38]
A API está retornando o seguinte erro:

```
{
message: "Quantidade inválida de requisições. Usuários sem token podem fazer apenas 500 requisições por dia"
}
```

Como faço para conseguir um token?

**Comment by deividfortuna** [comment]
Ainda estou trabalhando em um portal para fazer o registro. Por enquanto posso fazer manualmente.
Manda um email para mim deividfortuna+fipe@gmail.com com seus dados de email e nome que faço o registro manualmente.

**Comment by gabrielrosas** [comment]
Coloquei o Token... Porem agora a Mensagem mudou para:

```
{
"message":"Quantidade inválida de requisições. Você pode fazer apenas 5000 requisições por dia"
} 
```

Eu tenho um Script de importação. Eu faço a importação uma vez por mês. 5000 request não é o suficiente para fazer a importação da base toda. Tem algo que eu possa fazer?

**Comment by bruno-rodrigues** [comment]
@deividfortuna me consegue uma chave?
Bruno Rodrigues
brunojti@gmail.com

**Comment by lucazin** [comment]
Me Consegue uma chave Amigo ? Qts solicitacoes posso fazer por mes ?

**Comment by RichardFarenayte** [comment]
Pode me fornecer uma chave?

**Comment by paulalopes21** [comment]
Gostaria de uma chave de acesso, por favor.

**Comment by marcelo-ribeiro** [comment]
Erro ao obter as marcas.
O token é obrigatório agora?

![captura de tela 2018-08-08 as 18 55 27](https://user-images.githubusercontent.com/8428129/43866607-b8f27e14-9b3c-11e8-9321-5220e4188ac5.png)
![captura de tela 2018-08-08 as 18 55 38](https://user-images.githubusercontent.com/8428129/43866609-ba7a85c4-9b3c-11e8-9894-b243c1d2a37a.png)

**Comment by victortacon** [comment]
Bom dia!
A API está em funcionamento?
Como faço para conseguir uma chave?

**Comment by marcelo-ribeiro** [comment]
> Ainda estou trabalhando em um portal para fazer o registro. Por enquanto posso fazer manualmente.
> Manda um email para mim com seus dados de email e nome que faço o registro manualmente.

Como faço para conseguir um token?
Qual seu e-mail?

**Comment by victortacon** [comment]
Olá,

Meu e-mail é victortacon@gmail.com

Obrigado

Em sex, 15 de fev de 2019 14:39, Marcelo Ribeiro <notifications@github.com
escreveu:

**Comment by carneirocorp** [comment]
Olá,

Como faço pra obter uma chave ?

Meu email é alexandre.carneiro@gmail

**Comment by ednilsonamaral** [comment]
Essa API ainda funciona? Esta atualizada? Se sim, consigo uma chave?

**Comment by deividfortuna** [comment]
@ednilsonamaral API está online e não precisa de chave...
