### ISSUE TITLE
Retorno de valor inválido na consulta de ano

### ISSUE THREAD

**Issue by bruno-rodrigues** [deividfortuna/fipe#4]
Para alguns item o valor de retorno da ano é mais ou menos assim `32000 Gasolina`, quando deveria ser algo do tipo: `2017 Gasolina`.

Sei que não é problema da API que é excelente, mas gostaria de saber se vc sabe o que significa esse retorno.

Parabéns pelo excelente trabalho. 😄

**Comment by deividfortuna** [comment]
Muito obrigado @bruno-rodrigues.
Você pode me mandar a marca e modelo que estão retornando esse valor?

**Comment by bruno-rodrigues** [comment]
No meu DB existem mais de 1000 registros que iniciam com esse `32%`.

Um deles é o `Audi A4 1.8 Avant Turbo Tip./ Multitronic`.

Perdão pelo atraso, eu vi a resposta e achei que eu ja havia a respondido... :(
[]'s

**Comment by deividfortuna** [comment]
Sem problemas @bruno-rodrigues 

Dei uma alhada aqui e a FIPE usa esse código para representar o Zero KM. Não faz muito sentido mas é isso mesmo :see_no_evil:

Abraço, qualquer duvida estamos ai :sunglasses:

**Comment by bruno-rodrigues** [comment]
Fala @deividfortuna, aqui estou novamente...
Será que o `Código` desse registro de 0km `(32000-1)` muda de um ano pro outro?
Ou sempre que sai uma nova versao de 0km eles atualizam apenas o valor desse registro?

**Comment by deividfortuna** [comment]
@bruno-rodrigues não tenho certeza mas acho que o 32000-1 é sempre o 0km do ano atual no ano seguinte ele entra com um outro registro tendo uma identificação própria.

Desculpa a demora. Abraço
