### ISSUE TITLE
Api fora do ar?

### ISSUE THREAD

**Issue by fredderiks** [deividfortuna/fipe#41]
Bom dia. 
A API está fora do ar? 
Estou recebendo erro 404 ao tentar fazer uma consulta.

**Comment by jpdesignerrio** [comment]
Como os resultados do próprio site também estão vazios (https://deividfortuna.github.io/fipe/), caiu mesmo.

**Comment by deividfortuna** [comment]
Olá,
Investiguei e parece que houve alguma mudança na FIPE estou trabalhando para corrigir nas próximas horas.

Aviso aqui quando estiver ok.
Grande abraço e feliz ano novo.

**Comment by deividfortuna** [comment]
Corrigido!
