### ISSUE TITLE
Trazer Imagem

### ISSUE THREAD

**Issue by caioorg** [deividfortuna/fipe#43]
Como futura melhoria seria bom, trazer a imagem do veiculo.

**Comment by jsouza678** [comment]
Também gostaria... o que acha Deivid? acho que a Fipe disponibilia as fotos dos veículos também no BD deles

**Comment by jsuceir** [comment]
uai é só usar o google Imagem no seu codigo

**Comment by pauloamigoni** [comment]
Infelizmente a FIPE não disponibiliza a imagem do veículo, imagina o trabalho que eles vão ter de ter um banco de imagem com todas cores, anos, modelos... e tem modelos como a marca By Cristo que é em pequena escala.... isso impossibilitando o envio das imagens

**Comment by deividfortuna** [comment]
A idea é legal mas inviável para mim, poderia ser um projeto separada para alguém?
Uma API que voce passa o código FIPE e retorna a imagem?
