### ISSUE TITLE
API HTTP REST fora do ar?

### ISSUE THREAD

**Issue by dyogophoenix** [deividfortuna/fipe#44]
A API está fora do ar?
Estou recebendo erro 404 ao tentar fazer uma consulta, até mesmo a própria página se encontra sem resultados de retorno. [deividfortuna.github.io/fipe](https://deividfortuna.github.io/fipe/)

**Comment by fredderiks** [comment]
Também estou recebendo o mesmo erro 404 ao fazer uma consulta.

**Comment by dyogophoenix** [comment]
Retornou!

**Comment by deividfortuna** [comment]
A FIPE esta fazendo algumas tentativas de bloqueio a consultas, estou fazendo o possível para driblar isso no momento.

**Comment by deividfortuna** [comment]
Está funcionando normalmente...
