### ISSUE TITLE
Não consigo mais converter os valores dos carros em número

### ISSUE THREAD

**Issue by henriquemirai** [deividfortuna/fipe#45]
Até agora há pouco (31/07/19 - 11h56) eu conseguia pegar o valor do carro que vinha como string e transformar em número pra poder manipular, mas do nada parou de funcionar! Não importa se eu use number, parseInt ou parseFloat, só recebo NaN como resultado. Ele só mostra o valor corretamente como string.

**Comment by henriquemirai** [comment]
Agora o funcionamento está intermitente (12h21)

**Comment by deividfortuna** [comment]
@henriquemirai O retorno do valor é uma string, examplo: "R$ 92.468,00"  então se você deseja converter para um float in javascript eu recomendo algo como `+"R$ 92.468,00".replace("R$ ", "").replace(".", "").replace(",", ".")`
