### ISSUE TITLE
API FORA DO AR

### ISSUE THREAD

**Issue by danilo-silv** [deividfortuna/fipe#46]
Boa tarde Deivid, fiz uma requisição na api e a mesma me retornou com o Status 404
Pode nos ajudar dando uma olhada?
Estou tentando bater na URL: https://parallelum.com.br/fipe/api/v1/carros/marcas
Resposta: 
![image](https://user-images.githubusercontent.com/40410738/67701706-30731a00-f98f-11e9-854b-bde7e5c80c8e.png)

tentei bater via postman e recebi esse erro:
![Capturar](https://user-images.githubusercontent.com/40410738/67701586-f6097d00-f98e-11e9-806d-8b8494ade062.PNG)

**Comment by lucasferreiraestevam** [comment]
> Olá, boa tarde. A própria tabela fipe está offline.
> Liguei para lá, e ainda estão resolvendo os problemas do site. Espero que não mude nada na conexão da api .. estava usando para uma monografia rsrs. De qualquer forma espero que tenha como guardar a tabela fipe localmente, porque depender de ela estar online sempre é complicado.

A fipe voltou ao normal, mesmo assim requests para as rotas https://parallelum.com.br/fipe/api/v1 continuam retornando 404.

![Captura de Tela 2019-10-28 às 16 57 01](https://user-images.githubusercontent.com/12140708/67713175-13951180-f9a4-11e9-9441-7642fdc16247.png)

**Comment by deividfortuna** [comment]
Opa, parece que houve uma instabilidade com o servidor da FIPE. Estou analisando uma solução para o problema, espero ter alguma resposta nas próximas horas...

**Comment by jsouza678** [comment]
Muito obrigado por se prontificar a resolver! Obrigado por disponibilizar essa api!

**Comment by lucasferreiraestevam** [comment]
@deividfortuna obrigado 👏

**Comment by deividfortuna** [comment]
@lucasferreiraestevam  @jsouza678 @danilo-silv está de volta! 

Considere me pagar uma cerveja 🍺😎 
[![Make a donation](https://www.paypalobjects.com/pt_BR/BR/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QUPMYWH6XAC5G)

**Comment by danilo-silv** [comment]
> @lucasferreiraestevam @jsouza678 @danilo-silv está de volta!
> 
> Considere me pagar uma cerveja 🍺😎 
> [![Make a donation](https://camo.githubusercontent.com/f7b339c769c56e1054ffd43f22dc78b8a3d259e1/68747470733a2f2f7777772e70617970616c6f626a656374732e636f6d2f70745f42522f42522f692f62746e2f62746e5f646f6e61746543435f4c472e676966)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QUPMYWH6XAC5G)

Merece muito, vlw Deivid !!

**Comment by JuniorCosta** [comment]
Boa tarde @deividfortuna tudo blza ? Cara parece que esta off novamente a API. Poderia verificar o que aconteceu? Abraço!
