### ISSUE TITLE
link to show all details of each car

### ISSUE THREAD

**Issue by keshav-gupta98** [deividfortuna/fipe#47]
I am not able to fetch all cars data.Please give me the link which i should use to fetch data with all the keys of all cars.

**Comment by deividfortuna** [comment]
Hi @keshav-gupta98 at this moment is not possible fetch the entire database. My API use web scraping to get the data from the official web site so download the entire thing would generate a considerable traffic to their website.

Please take a look in the API documentation: https://deividfortuna.github.io/fipe/
Kindly regards
