### ISSUE TITLE
API não está funcionando

### ISSUE THREAD

**Issue by keshav-gupta98** [deividfortuna/fipe#48]
mostrando o tamanho da matriz 0 no link fornecido
https://deividfortuna.github.io/fipe/

**Comment by elvistjw** [comment]
Erro 404 na requisição.

**Comment by keshav-gupta98** [comment]
Por que está chegando? Estava funcionando bem um dia antes.

**Comment by elvistjw** [comment]
> Por que está chegando? Estava funcionando bem um dia antes.

Mas hoje fui testar e não está pegando

**Comment by keshav-gupta98** [comment]
Estou solicitando a todos que encontrem a solução o mais rápido possível

**Comment by deividfortuna** [comment]
Obrigado por me avisarem. Estou analisando o problema, assim que eu tiver mais informações deixo vocês saberem por aqui.

**Comment by keshav-gupta98** [comment]
@deividfortuna Remova esse problema o mais rápido possível, pois tenho muitas entrevistas de emprego nas próximas duas semanas e preciso mostrar meu projeto.

**Comment by lucasferreiraestevam** [comment]
> Obrigado por me avisarem. Estou analisando o problema, assim que eu tiver mais informações deixo vocês saberem por aqui.

🙏 valeu Deivid

**Comment by lvffilho** [comment]
@deividfortuna Se precisar de uma mão ou contribuição par algo é só dar um grito.

**Comment by gustavo-cunha** [comment]
Olá @deividfortuna, também me coloco a disposição se precisar de ajuda. Essa API é muito útil pra nós da Roisoft.

**Comment by lucasferreiraestevam** [comment]
@deividfortuna se precisar de ajuda estamos a disposição.

**Comment by keshav-gupta98** [comment]
@deividfortuna por favor, conte-nos sobre a situação. Quanto tempo levará?

**Comment by keshav-gupta98** [comment]
paise xhahiye toh btaadio bhai

**Comment by deividfortuna** [comment]
Aparatemente houve alguma atualizacão no site da Fipe o que fez o script parar de funcionar, tirei mais informações nas próximas 48 horas.
Obrigado pela compreensão e considere me pagar uma cerveja e ajudar a manter a API online 

[![Make a donation](https://www.paypalobjects.com/pt_BR/BR/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QUPMYWH6XAC5G)

**Comment by lucasferreiraestevam** [comment]
> Aparatemente houve alguma atualizacão no site da Fipe o que fez o script parar de funcionar, tirei mais informações nas próximas 48 horas.
> Obrigado pela compreensão e considere me pagar uma cerveja e ajudar a manter a API online
> 
> [![Make a donation](https://camo.githubusercontent.com/f7b339c769c56e1054ffd43f22dc78b8a3d259e1/68747470733a2f2f7777772e70617970616c6f626a656374732e636f6d2f70745f42522f42522f692f62746e2f62746e5f646f6e61746543435f4c472e676966)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QUPMYWH6XAC5G)

Beleza @deividfortuna salva nóis, vou doar uma grana pra ajudar ai, se precisar de ajuda pra manter a API online estamos a disposição também.

**Comment by deividfortuna** [comment]
Como eu suspeitava o site da Fipe recebeu uma atualização. Atualmente a API está parcialmente funcionando e estou trabalhando em uma solução completa.

**Comment by deividfortuna** [comment]
Pessoal a API está funcionando normalmente. Por favor me avisem se tiverem alguma dificuldade.

Me ajudem a manter o projeto online fazendo uma doação:
[![Make a donation](https://www.paypalobjects.com/pt_BR/BR/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QUPMYWH6XAC5G)
