### ISSUE TITLE
Trazer os modelos, baseado num ano escolhido

### ISSUE THREAD

**Issue by fabianochaves** [deividfortuna/fipe#50]
Boa tarde,
Existe a possibilidade de incrementar a seguinte melhoria:

Selecionar a Marca, em seguida selecionar um ano específico com seu combustível (Ex: 2015 Gasolina) e com isso retornar os modelos daquela marca, que estejam dentro do ano e combustível escolhido.

Isso facilita na procura de um modelo, por exemplo VW Gol, que a lista é grande, assim como outros modelos também.

**Comment by ricardoalvescarvalho** [comment]
Também gostaria dessa possibilidade.

**Comment by deividfortuna** [comment]
ola @fabianochaves @ricardoalvescarvalho 
acabei de implementar os endpoints:

Retorna os anos para marcas: `https://parallelum.com.br/fipe/api/v2/carros/brands/48/years`
Retorna os modelos para o ano: `https://parallelum.com.br/fipe/api/v2/carros/brands/48/years/2018-1/models`

Ainda nao atualizei a documentação.
Aguardo o see feedback, abraco.

**Comment by ricardoalvescarvalho** [comment]
Excelente Deivid! Muito obrigado, será muito útil.

Saudações,

Ricardo


Em qui., 2 de jun. de 2022 às 06:18, Deivid Fortuna <
***@***.***> escreveu:
