### ISSUE TITLE
Consulta através do código fipe

### ISSUE THREAD

**Issue by diegoarantes** [deividfortuna/fipe#54]
Teria alguma maneira de consultar apenas com o código fipe ?

**Comment by deividfortuna** [comment]
Ainda não, mas é uma boa sugestão de funcionalidade...

**Comment by deividfortuna** [comment]
Disponivel através desse endpoint documentado aqui: https://deividfortuna.github.io/fipe/v2/#operation/GetInfoByFipeCode

https://parallelum.com.br/fipe/api/v2/{vehicleType}/{fipeCode}/years/{yearId}
