### ISSUE TITLE
Escolher mês/tabela de referência

### ISSUE THREAD

**Issue by yancorrea1995** [deividfortuna/fipe#55]
Olá @deividfortuna como vai?

Gostaria de saber se tem como habilitar para passarmos o código do mês de referencia como parâmetro na busca de valor? Na API ele utiliza a última tabela de referência (por exemplo 251), mas eu gostaria de passar como parâmetro esse codigo, pode ser opcional, assim não quebra a API pra quem já usa. Se puder me dar uma ajuda, é um pouco urgente. Valeu, abraço e obrigado pelo ótimo trabalho que fez com a API.

**Comment by vic131** [comment]
> Olá @deividfortuna como vai?
> 
> Gostaria de saber se tem como habilitar para passarmos o código do mês de referencia como parâmetro na busca de valor? Na API ele utiliza a última tabela de referência (por exemplo 251), mas eu gostaria de passar como parâmetro esse codigo, pode ser opcional, assim não quebra a API pra quem já usa. Se puder me dar uma ajuda, é um pouco urgente. Valeu, abraço e obrigado pelo ótimo trabalho que fez com a API.

Estou na mesma situação agora. Alguma dica ?

**Comment by deividfortuna** [comment]
Gostei da ideia, desculpa demorar tanto para responder.
Algo como `api/v1/carros/marcas/59/modelos/5940/anos/2014-3?referencia=251`?

**Comment by michaelfv** [comment]
> Gostei da ideia, desculpa demorar tanto para responder.
> Algo como `api/v1/carros/marcas/59/modelos/5940/anos/2014-3?referencia=251`?

Seria perfeito isso!

**Comment by deividfortuna** [comment]
Opa galera acabei me envolvendo com outros projetos e esqueci dessa feature, mas tive um tempo livre e implementei hoje a API. Infelizmente nao tive tempo para atualizar a library mas se voces usam a API diretamente acho que vai solucionar o problema.

Agora voce pode passar um query parameter `referencia` com o codigo da tabela de referencia na hora de consultar os precos. 

https://parallelum.com.br/fipe/api/v1/referencias
```json
[
{
"codigo": 273,
"mes": "agosto/2021 "
},
{
"codigo": 272,
"mes": "julho/2021 "
},
...
]
```

https://parallelum.com.br/fipe/api/v1/carros/marcas/59/modelos/5940/anos/2014-3?referencia=271
```json
{
"Valor": "R$ 102.451,00",
"Marca": "VW - VolksWagen",
"Modelo": "AMAROK High.CD 2.0 16V TDI 4x4 Dies. Aut",
"AnoModelo": 2014,
"Combustivel": "Diesel",
"CodigoFipe": "005340-6",
"MesReferencia": "junho de 2021 ",
"TipoVeiculo": 1,
"SiglaCombustivel": "D"
}
```

https://parallelum.com.br/fipe/api/v1/carros/marcas/59/modelos/5940/anos/2014-3
```json
{
"Valor": "R$ 109.888,00",
"Marca": "VW - VolksWagen",
"Modelo": "AMAROK High.CD 2.0 16V TDI 4x4 Dies. Aut",
"AnoModelo": 2014,
"Combustivel": "Diesel",
"CodigoFipe": "005340-6",
"MesReferencia": "agosto de 2021 ",
"TipoVeiculo": 1,
"SiglaCombustivel": "D"
}
```

Abraco, no aguardo do seu feedback
