### ISSUE TITLE
Fazer download do banco de dados para uso sem internet

### ISSUE THREAD

**Issue by marcos93net** [deividfortuna/fipe#56]
Tem como eu fazer o download do banco de dados para eu não ter que ficar fazendo requisições no seu servidor e também poder usar esses dados sem internet? Dessa forma eu faria apenas 1 download mensalmente para atualizar os valores.

**Comment by vic131** [comment]
Do banco de dados mensal pronto eu não achei nada, mas dá pra construir um, fazendo uma requisicao de cada vez.Aqui explica um pouco : https://documenter.getpostman.com/view/7064033/SWT5jMGk#1add99a8-7c89-41b5-ab7e-8c8f20b40194

**Comment by vic131** [comment]
> Tem como eu fazer o download do banco de dados para eu não ter que ficar fazendo requisições no seu servidor e também poder usar esses dados sem internet? Dessa forma eu faria apenas 1 download mensalmente para atualizar os valores.

Do banco de dados mensal pronto eu não achei nada, mas dá pra construir um, fazendo uma requisicao de cada vez.Aqui explica um pouco : https://documenter.getpostman.com/view/7064033/SWT5jMGk#1add99a8-7c89-41b5-ab7e-8c8f20b40194

**Comment by deividfortuna** [comment]
@marcos93net Infelizmente não ainda não é possível fazer o download da tabela inteira. 
Existem uma serie de coisas que devemos levar em consideração para fazer isso. Irei fechar o issue pois não esta em meus planos implementar isso por agora.
