### ISSUE TITLE
Api fora do ar?

### ISSUE THREAD

**Issue by lucasjeronimo** [deividfortuna/fipe#57]
A Api é excelente, 
mas aparentemente está fora do ar, nem acessando pelo navegador está funcionando, diz que as paginas não existem, mudou algo. Olhei na documentação da Api, porém não vi nada de diferente.

**Comment by marcelogrsp** [comment]
Aparentemente esta fora do ar. Boca santa a minha! Falei ontem para um colega que nao poderiamos confiar na API nao oficial, ta ai, no dia seguinte ela cai! @deividfortuna

**Comment by lucasjeronimo** [comment]
Bah, verdade, nem pensei em tentar acessar o site da Fipe.

**Comment by enriqueboni80** [comment]
Putz. Fiz todo um trabalho da pós graduação utilizando essa API (com a data de entrega pro dia 05/04) e agora a API não funciona. tenso!

**Comment by vemprabou** [comment]
Tbm utilizo esta API, sempre funciona bem.
Ja vi problemas quando, existem atualizações na FIPE.
Mas hoje ela esta OFF msm.

**Comment by backofficesolucoes** [comment]
Está funcionando com a requisição via POST

![image](https://user-images.githubusercontent.com/58264334/78382953-fb0dd080-75ad-11ea-8289-943e0dc45ad4.png)

**Comment by CarlosCelesti** [comment]
Boa tarde...

Não sei se ajuda para esta api especificamente....

Mas como a url oficial da api Fipe é esta: -> veiculos.fipe.org.br/api/veiculos ...

No meu caso eu notei que minhas chamadas para api estavam indo ser SSL (nem sei pq)....

Mas eu troquei http por https na url de chamada e passou a rodar.... no meu caso eu posso dizer que antes ia sem ssl agora não vai mais.....

Como disse, não sei se ajudas os colegas aqui, no meu caso acabei de resolver e está funcionando, ok,

abcs.

**Comment by tdias25** [comment]
Caiu pra mim também, voltará ou o projeto foi fechado?

**Comment by backofficesolucoes** [comment]
A rota http://veiculos.fipe.org.br/api/veiculos/ConsultarTabelaDeReferencia não existe mais, estou buscando alguma rota alternativa

**Comment by CarlosCelesti** [comment]
É estranho....mas eu olhei no próprio site da fipe e a tora parece a mesma...

Onde eu uso eu acho a mesma rota para montar a tabela de referência atual: http://veiculos.fipe.org.br/api/veiculos/ConsultarTabelaDeReferencia só quem https...

Tem a questão do cabeçalho também:

Vou dar o exemplo do que tenho aqui:

header("Content-Type: application/json; charset=utf-8");
function FipeJson($resource, $data = null)
{
    $url = "https://veiculos.fipe.org.br/api/veiculos";
    $header = [
        "Cache-Control: no-cache",
        "Content-Type: application/json",
        "Host: veiculos.fipe.org.br",
        "Referer: https://veiculos.fipe.org.br"
    ];
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url . "/" . $resource);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
    $output = curl_exec($ch);
    curl_close($ch);
    return json_encode($output);
}
....

então abaixo é recuperado as tabelas de referências:
$tabela_referencia = FipeJson("ConsultarTabelaDeReferencia");


pra mim roda ok

**Comment by backofficesolucoes** [comment]
Funcionando galera

**https://veiculos.fipe.org.br/api/veiculos//ConsultarTabelaDeReferencia**

**Comment by enriqueboni80** [comment]
amigos, mas infelizmente minha aplicação não esta buscando diretamente da fipe e sim pela url https://deividfortuna.github.io/fipe/
visto que tenho que entregar um trabalho utilizando essa api no dia 05/04, não sei se começo outro projeto ou espero pra ver se volta

**Comment by lucasjeronimo** [comment]
Eu uso outro como backup, porém a do Deivid é mais rápida e melhor.
Da uma conferida nessa: http://fipeapi.appspot.com/
Pelo menos da pra ti adaptar no teu trabalho.

**Comment by vemprabou** [comment]
> Eu uso outro como backup, porém a do Deivid é mais rápida e melhor.
> Da uma conferida nessa: http://fipeapi.appspot.com/
> Pelo menos da pra ti adaptar no teu trabalho.

Rapaz, muito obrigado, me ajudou muito.
Implantei essa api tbm pra minhas consultas, ai quando a do deividfortuna estiver fora, busco automático na appspot.

**Comment by marcelogrsp** [comment]
@deividfortuna qual a rota para POST que retornara os dados do veículo contendo preço, por favor?

Estou tentando a seguinte:
```
curl --location --request POST 'https://veiculos.fipe.org.br/api/veiculo/43/1781/2009-1' \
--form 'codigoTabelaReferencia=253' \
--form 'codigoTipoVeiculo=1' \
--form 'codigoMarca=43' \
--form 'codigoVeiculo=1781' \
--form 'codigoModelo=2009-1'
```

**Comment by danbonattis** [comment]
> Putz. Fiz todo um trabalho da pós graduação utilizando essa API (com a data de entrega pro dia 05/04) e agora a API não funciona. tenso!

Cara, muda pra HTTPS que dá certo!
Ex: https://veiculos.fipe.org.br/api/veiculos/ConsultarTabelaDeReferencia

**Comment by marcelogrsp** [comment]
@enriqueboni80 
Use as rotas como nos exemplos a seguir:

### Consultar marcas

```js
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'https://veiculos.fipe.org.br/api/veiculos/ConsultarMarcas',
  'headers': {
    'Host': 'veiculos.fipe.org.br',
    'Referer': 'http://veiculos.fipe.org.br',
    'Content-Type': ['application/json', 'text/plain']
  },
  body: "{\n\t\"codigoTabelaReferencia\": 231,\n\t\"codigoTipoVeiculo\": 1\n}"

};
request(options, function (error, response) { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```

### Consultar modelos

```js
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'http://veiculos.fipe.org.br/api/veiculos/ConsultarModelos',
  'headers': {
    'Host': 'veiculos.fipe.org.br',
    'Referer': 'http://veiculos.fipe.org.br',
    'Content-Type': ['application/json', 'text/plain']
  },
  body: "{\n\t\"codigoTabelaReferencia\": 231,\n\t\"codigoTipoVeiculo\": 1,\n\t\"codigoMarca\": 26\n}"

};
request(options, function (error, response) { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```

### Consultar ano-modelo

```js
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'https://veiculos.fipe.org.br/api/veiculos/ConsultarAnoModelo',
  'headers': {
    'Host': 'veiculos.fipe.org.br',
    'Referer': 'http://veiculos.fipe.org.br',
    'Content-Type': ['application/json', 'text/plain']
  },
  body: "{\n\t\"codigoTabelaReferencia\": 231,\n\t\"codigoTipoVeiculo\": 1,\n\t\"codigoMarca\": 26,\n\t\"codigoModelo\": 4403\n}"

};
request(options, function (error, response) { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```

### Consultar modelos atraves dos anos

```js
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'https://veiculos.fipe.org.br/api/veiculos/ConsultarModelosAtravesDoAno',
  'headers': {
    'Host': 'veiculos.fipe.org.br',
    'Referer': 'http://veiculos.fipe.org.br',
    'Content-Type': ['application/json', 'text/plain']
  },
  body: "{\n\t\"codigoTabelaReferencia\": 231,\n\t\"codigoTipoVeiculo\": 1,\n\t\"codigoMarca\": 26,\n\t\"ano\": \"2011-1\",\n\t\"codigoTipoCombustivel\": 1,\n\t\"anoModelo\": 2011\n}"

};
request(options, function (error, response) { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```

### Consultar valor com todos os parametros

```js
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'https://veiculos.fipe.org.br/api/veiculos/ConsultarValorComTodosParametros',
  'headers': {
    'Host': 'veiculos.fipe.org.br',
    'Referer': 'http://veiculos.fipe.org.br',
    'Content-Type': ['application/json', 'text/plain']
  },
  body: "{\n\t\"codigoTabelaReferencia\": 231,\n\t\"codigoTipoVeiculo\": 1,\n\t\"codigoMarca\": 26,\n\t\"ano\": \"2011-1\",\n\t\"codigoTipoCombustivel\": 1,\n\t\"anoModelo\": 2011,\n\t\"codigoModelo\": 4403,\n\t\"tipoConsulta\": \"tradicional\"\n}"

};
request(options, function (error, response) { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```

**Comment by deividfortuna** [comment]
API está online novamente.
