### ISSUE TITLE
Erro 500 ao consultar API

### ISSUE THREAD

**Issue by Ismadrade** [deividfortuna/fipe#59]
Ola @deividfortuna tudo bem?
Estou desenvolvendo uma aplicação usando sua API para consultar as marcas e modelos do carro. Hoje de manha a API está me retornando o seguinte erro com status 500: 
{
  "message": "array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead"
}
Tens alguma previsão de corrigir isso? Ou está sendo feita alguma alteração na estrutura ou mapeamento da API? Se puder me adiantar, pois ja tenho outras aplicações que fazem o uso da sua API.

**Comment by diogo-palma** [comment]
verdade aqui comigo tb, vou ver se consigo utilizar esse codigo da api

**Comment by zgabrielschmidt** [comment]
também estou recebendo erro 500

**Comment by patrick-silva** [comment]
tbm estou na mesma

**Comment by laerciocrestani** [comment]
array_key_exists() is deprecated on objects in PHP 7.4 ...

É bem possível que foi atualizado o PHP, ai matou o serviço.

**Comment by Ismadrade** [comment]
> array_key_exists() is deprecated on objects in PHP 7.4 ...
> 
> É bem possível que foi atualizado o PHP, ai matou o serviço.

Pensei nisso tbm. Só que eu não manjo nada de php, se não tentava corrigir. Estou refazendo uma aplicação web que foi feita em jsp e servlet pra uma nova em Vue e Spring. Como temos um cadastro de veículos, após selecionar o tipo do carro, consumimos a API pra pegar a marca, em seguida o modelo e a versão. Até achei que fosse um bug meu durante o desenvolvimento, mas vi que no nosso sistema antigo também esta dando erro. 
![image](https://user-images.githubusercontent.com/52476687/105210453-d2010100-5b29-11eb-92ba-a30a308ea439.png)

**Comment by laerciocrestani** [comment]
Legal @Ismadrade, poisé vou ver se dou um FORK e vejo aqui, quanto ai teu Theme Web, tu ta usando o MD?

**Comment by diogo-palma** [comment]
dei uma olhada no codigo, a api é interna não da pra modificar o codigo dela..

**Comment by laerciocrestani** [comment]
Vem de **https://parallelum.com.br/fipe/api/v1/** essa lib. Vou implementar a v2 e atribuir de lá.

**Comment by Ismadrade** [comment]
> Legal @Ismadrade, poisé vou ver se dou um FORK e vejo aqui, quanto ai teu Theme Web, tu ta usando o MD?

Estou usando o framework da vuetify. Se não me engano, da pra usar em conjunto com Laravel. Se for usar vue em alguma aplicação no futuro, fica a dica.

**Comment by deividfortuna** [comment]
Muito obrigado por reportar o problema. Provavelmente esta acontecendo devido a atualização do PHP sim. Infelizmente estou no trabalho agora e só vou poder corrigir quando sair do escritório.

**Comment by Ismadrade** [comment]
Tranquilo @deividfortuna  :)

**Comment by diogo-palma** [comment]
@deividfortuna tem a possibilidade de você me passar seu contato do whats?

**Comment by fabriciops** [comment]
Algo que possamos fazer para ajudar ? @deividfortuna

**Comment by JonilsonC** [comment]
Boa tarde, @deividfortuna  tbm utilizo sua API, se tiver algo que possamos contribuir, pode contar amigo!

**Comment by stewartcintra** [comment]
tbm utilizo estou com mesmo problema

**Comment by adryel97** [comment]
Comigo também estou tendo este mesmo problema. Espero que consiga concertar.

**Comment by ewertont** [comment]
@deividfortuna, bom dia colega! necessita de alguma ajuda? pode contar conosco! abraços!

**Comment by ramagalhaes** [comment]
Fala @deividfortuna, tem previsão pra corrigir esse bug, irmão? Abraços!

**Comment by deividfortuna** [comment]
Problema corrigido, tem como alguem confirmar para mim?

**Comment by ramagalhaes** [comment]
Ta funcionando sim!!

**Comment by deividfortuna** [comment]
API está no ar novamente! Obrigado por me avisar e por favor considere me pagar uma cerveja e ajudar a manter a API online 🙏 

[![Make a donation](https://www.paypalobjects.com/pt_BR/BR/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QUPMYWH6XAC5G)

**Comment by JonilsonC** [comment]
Obrigado @deividfortuna  por voltar a disponibilizar a API. Como gratidão pelo seu trabalho, realizei uma doação. Peço a todos que vieram aqui e que utilizam a API que como gratidão realize uma doação para o @deividfortuna  continuar mantendo a API em funcionamento. Mais uma vez, muito obrigado pelo excelente trabalho @deividfortuna . Abraços camarada!
