### ISSUE TITLE
URL de acesso a API retornando erro 404

### ISSUE THREAD

**Issue by dorianneto** [deividfortuna/fipe#6]
Ao tentar consumir a api através da url https://fipe-parallelum.rhcloud.com/api/v1 está retornando erro 404.

**Comment by deividfortuna** [comment]
E ai @dorianneto 
Essa url nomralmente retorna um 404 vou mudar isso na próxima versão. 
Da uma olhada aqui: http://deividfortuna.github.io/fipe/

Tente essa url:
https://fipe-parallelum.rhcloud.com/api/v1/carros/marcas

O servidor da FIPE está com alguma instabilidades e notei que tenho um bug na API que esta sobrescrevendo o cache com um 404 com body vazio quando a FIPE está offline. Então vou deixar esse issue aqui para me lembrar de corrigir.

Espero ter ajudado :neckbeard:

**Comment by dorianneto** [comment]
Show @deividfortuna !

Onde você está sobrescrevendo o cache com um 404? Aproveito e corrijo logo :)

**Comment by deividfortuna** [comment]
@dorianneto é no no webservice...

**Comment by dorianneto** [comment]
;)

**Comment by deividfortuna** [comment]
Eu corrigi esse bug na API. Acredito que não voltará a ocorrer, caso volte por favor me avise :sweat_smile:
