### ISSUE TITLE
 Erro: 404 Page Not Found, ao buscar veículos do tipo carro e da marca VW - VolksWagen.

### ISSUE THREAD

**Issue by brConde85** [deividfortuna/fipe#63]
Ao realizar uma busca com veículos do tipo carro e da marca VW - VolksWagen, ocorre um erro: 404 Page Not Found.
Esse foi o caminho utilizado: https://parallelum.com.br/fipe/api/v1/carros/marcas/59/modelos

**Comment by joaomoraes83** [comment]
Percebi o mesmo erro!

**Comment by deividfortuna** [comment]
Fixed
