### ISSUE TITLE
Inconsistência nos erros HTTP retornados

### ISSUE THREAD

**Issue by huberemanuel** [deividfortuna/fipe#66]
Olá, parabéns pela iniciativa e pela disponibilização do serviço.

Quando tento acessar essa URL, por exemplo (https://parallelum.com.br/fipe/api/v1/motos/marcas/145/modelos/8677/anos/2020-1?referencia=279), em alguns momentos recebo erro 500, em outros 404 e também recebo a resposta 200 com os dados do veículo.

**Comment by deividfortuna** [comment]
Problema resolvido
