### ISSUE TITLE
boa noite, a api esta fora do ar ?

### ISSUE THREAD

**Issue by Guilherme-Geraldo2106** [deividfortuna/fipe#67]
ola, varios veiculos estão retornando erro 404, apenas alguns não retornaram o erro

**Comment by deividfortuna** [comment]
Oi Guilherme,
pode mandar uma URL que esta falhando como exemplo?

**Comment by Guilherme-Geraldo2106** [comment]
Boa tarde Deivid, voltou a funcionar, ficou fora por pouco tempo

Em sex., 17 de fev. de 2023 00:08, Deivid Fortuna ***@***.***>
escreveu:

**Comment by deividfortuna** [comment]
Infelizmente o servidor as vezes não da conta de tantos acessos e pode ficar instável, infelizmente a única forma de resolver e contratando um novo provedor, mas ainda não recebo doações necessárias para isso.

**Comment by Guilherme-Geraldo2106** [comment]
Acho que não seria viável cobrar um valor fixo mensal ?  Usei sua api mais
para estudo em um site que estou desenvolvendo, se for para frente e eu
chegar a lancar ele de fato, farei doações constantes com prazer

Em sáb., 18 de fev. de 2023 01:50, Deivid Fortuna ***@***.***>
escreveu:

**Comment by deividfortuna** [comment]
Oi Guilherme, posso gerar um link para doações mensais no valor que voce achar adequado, me mantenha informado ☺️
