### ISSUE TITLE
API fora do ar

### ISSUE THREAD

**Issue by alsdigitalbauru** [deividfortuna/fipe#70]
Olá meu nobre amigo a API esta fora do ar, talvez se cabra-se uma pequena mensalidade, somente para manter um server ajudaria seu excelente trabalho.

desde de já agradeço por disponibilizar esta API de forma gratuita.

**Comment by luizfelipedev-agillity** [comment]
Concordo plenamente

**Comment by luizfelipedev-agillity** [comment]
10 reais que seja já ajudaria

**Comment by leojarts** [comment]
Se a questão for custo de hospedagem, eu posso hospedar em nosso servidor AWS 24x7, acabei de implementar a API de vocês, mas se tiver quedas realmente vou precisar buscar outra alternativa. Se quiser só me chamar no whats: 11989062645

**Comment by deividfortuna** [comment]
Infelizmente o provedor do servidor tirou do ar devido a quantidade de recursos o servidor estava consumindo. Estou negociando com o provedor para trazer a API. Aparentemente o plano atual não esta dando conta de segurar o uso.

Manterei voces informados ☺️

**Comment by luizfelipedev-agillity** [comment]
de quanto você precisa mensalmente
?

**Comment by leojarts** [comment]
Acho que a doação em si, não ajudaria garantir todo mês! O plano de assinatura seria mais efetivo neste caso! Nessa linha que o @luizfelipedev-agillity está comentando...

**Comment by luizfelipedev-agillity** [comment]
Não sei mas a curto prazo implementar um painel de licenças

**Comment by luizfelipedev-agillity** [comment]
eu uso isso para ativar ou inativar clientes aqui da minha ferramenta de motofretes

**Comment by deividfortuna** [comment]
Por volta de R$300 mensais para fazer o upgrade no servidor.

Uma das soluções seria isso ter um plano free com limitação e um mensalidade em conta para não dificultar ninguém, mas eu realmente gostaria que as pessoas que usam em produção fizessem doações espontâneas 🥹

**Comment by luizfelipedev-agillity** [comment]
isso no geral correto?  estou conversando com meu cliente aqui que usa a sua ferramenta vou enfatizar a necessidade disso para agregar a folha de mensalidade, acredito que os 300 eu nao consiga, mas assim que tiver uma posição informo aqui

**Comment by leojarts** [comment]
Vou fazer o mesmo com o meu cliente aqui para conseguir uma contribuição mensal também

**Comment by luizfelipedev-agillity** [comment]
mans, consegui garantir mensalmente (enquanto durar o sistema né kkkk) 50 pila para ajudar nessa empreitada ai, Deivid fica aqui uma força caso queira implementar o sistema de licenciamento, meu whats 11954431712

**Comment by bottazzo** [comment]
Concordo com uma mensalidade para manter o servidor. Porém me pegou desprevenido. Entendo o que está passando porém você tem uma previsão de quando consegue voltar a API ? Utilizo a API em tempo real em uma aplicação de produção e estou com uma grande problema. Preciso entender se passo a noite migrando para algum outro serviço ou se voltaremos ainda essa madrugada!

De qualquer forma, estou disponível para auxiliar no que for preciso, inclusive financeiramente.

**Comment by luizfelipedev-agillity** [comment]
senhores alguma novidade ?

**Comment by leojarts** [comment]
Meu cliente optou por escolher um serviço pago para termos mais garantias. Vlw pessoal

**Comment by souzahub** [comment]
Algum parecer?

**Comment by luizfelipedev-agillity** [comment]
ainda nada

**Comment by rafanake** [comment]
Não conseguiria disponibilizar o fonte ai nós mesmo hospedamos a API oq pode dar uma folga no seu server tb.

Muito obrigado pela API, tem de fato sido muito útil.

**Comment by olavomello** [comment]
@deividfortuna Se puder informe a estrutura do server necessária. Vou ver o que consigo por aqui também !

**Comment by deividfortuna** [comment]
Implementei a rate limit na API, provedor me deu 48hrs para retornar o serviço 🥹

**Comment by olavomello** [comment]
Booaaaa !!!
De qualquer forma passe as configs se puder. Derepente podemos ajudar a subir um server top pois os recursos são úteis para muitos.

**Comment by deividfortuna** [comment]
⚠️ ⚠️  Mudar para outro servidor privado esta fora de questão, pois não existe garantias que a pessoa manteria online indeterminadamente. Considere fazer uma doação mensal para que eu possa pagar um servidor melhor 🥹 ⚠️ ⚠️

**Comment by olavomello** [comment]
Faz sentido @deividfortuna

**Comment by claudioneves1981** [comment]
Acho que eu fui um pouco culpado kkk no dia que deu esse problema estava atualizando um projetinho pessoal usando essa api.dai de repente ela parou de funcionar, logo pensei acho que crashei a api da Fipe kkkk fiquei com isso na cabeça.acho que acabei fazendo muitas requisições na api e ela travou. Aí pensei fudeu, Espero que vc consiga resolver seu problema, vou tentar ajustar meu projetinho para não ocorrer algum problema de novo não quero me sentir culpado.

**Comment by marcelobm33** [comment]
Ola, utilizo tambem, e meu sistema travou ontem com esse ocorrido, tambem estou disposto a ajudar, para que possa contornar o problema o mais rapido possivel

**Comment by deividfortuna** [comment]
Estamos de volta galera!

**Comment by olavomello** [comment]
👏🏻👏🏻👏🏻

**Comment by deividfortuna** [comment]
Vou aproveitar para fazer um desabafo. 

Recebi dezenas de emails esses dois dias, infelizmente não consigo responder a todos, muito desses emails de pessoas reclamando que o serviço que eu forneço gratuitamente estava fora do ar e estava afetando o produto deles em produção, me pressionando para resolver o problema como se eu não estive fazendo o possível para resolver 🥺

Esse aqui é o meu painel de doação no PayPal dos últimos 90 dias:
<img width="1339" alt="Screenshot 2023-03-10 at 10 23 49 AM" src="https://user-images.githubusercontent.com/2691587/224163152-495911f3-51fc-4b08-8c2c-bde7ce518b3d.png">

Muito obrigado Luiz Felipe De Mattos, voce foi o único que decidiu contribuir!

Infelizmente poucas pessoas reconhecem o esforço que coloquei por anos para manter esse serviço online e gratuito. Sei que muitas pessoas abusam da API e acabam usando muitos recursos do servidor que mantenho, mas poucas, pouquíssimas ajudam a manter o projeto online.

A API vai continuar online mas acredito que terei que fazer algumas mudanças.

Atenciosamente,
Deivid

**Comment by luizfelipedev-agillity** [comment]
Deivid como falei antes man, voltando o serviço eu consigo te garantir pelo menos uns 50 Pila, compromisso aqui, vc tem meu whats

**Comment by marcelobm33** [comment]
Eu não contribui pq não manjo nada, me manda o link aqui nos comentários q faço minha parte ! O ideal era ter mensalidade para quem usa profissionalmente ! Aí não fica essa história de contribui e não contribui ! 
Os desenvolvedores lucram , merecidamente 
Os usuarios usam sem maiores complicações  

basicamente o capitalismo agindo 👀

**Comment by rep74joao** [comment]
@deividfortuna ta com erro a doacao irmao 

![image](https://user-images.githubusercontent.com/12641821/224186167-8b59f4be-d390-4334-be7d-7892792218eb.png)

**Comment by marcelobm33** [comment]
feito , vi que voltou a funcionar 

<img width="743" alt="Captura de Tela 2023-03-10 às 09 48 02" src="https://user-images.githubusercontent.com/66134406/224320090-a256ef1b-ca38-4e58-b2e7-23eeb24c2219.png">

**Comment by deividfortuna** [comment]
@marcelobm33 muito obrigado! Tive que remover o seu comentário pois tive informações sensíveis.

**Comment by deividfortuna** [comment]
Quem quiser ajudar e esta com problema no PayPal pode ajudar por fix:

![image](https://user-images.githubusercontent.com/2691587/224403522-ad886791-a06d-4b5c-abc7-c0400aa80f0a.png)

Chave: `00020126580014BR.GOV.BCB.PIX01360ba87ef2-ac4d-481a-bba8-dac0118895e65204000053039865802BR5925Deivid Fortuna de Azevedo6009SAO PAULO61080540900062240520HnlTSYwzcJCpm361n7be6304E4BF`

Link: https://nubank.com.br/pagar/1n7be/QBSPFkazaV

cc @rep74joao

**Comment by rep74joao** [comment]
@deividfortuna 
![WhatsApp Image 2023-03-10 at 16 42 31](https://user-images.githubusercontent.com/12641821/224412862-4e740f65-1964-4b90-92ee-2403f9cf49db.jpeg)

**Comment by ramonteiro** [comment]
Olá, pessoal. Também vou contribuir, mas uma dúvida. A response dos modelos para algumas marcas, como BMW/Audi/Mercedes, está retornando dados de Ano-Modelo (e.g. https://parallelum.com.br/fipe/api/v2/cars/brands/7/models)
Para outras marcas, como VW, está retornando normal. Seria isso uma sintoma da questão do servidor?

**Comment by deividfortuna** [comment]
Corrigido @ramonteiro

**Comment by mateusoliiveira** [comment]
Fala Deivid. Te dou uma sugestão: coloca um pix no site para doações. Fica mais dinâmico e rápido doar, embute um texto explicando as consequências do porque não doar pode ser ruim: serviço pode ficar indisponível ou lento, etc. Acredito que criar esse senso de urgência fará quem visita o site cogitar doar qualquer valor mesmo que simbólico.

**Comment by tekiros08** [comment]
Estou tentando usar essa api, apenas como treino. sou iniciante na progamação alguem consegue me ajudar?

**Comment by MarksEliel** [comment]
Web server is down
já fiz minha doação...

**Comment by luizfelipedev-agillity** [comment]
Ainda esta offline

**Comment by marcelobm33** [comment]
Oi, Deivid!! precisas de algum suporte $ para colocar em um servidor mais estavel ?

**Comment by marcelobm33** [comment]
<img width="810" alt="Captura de Tela 2023-06-21 às 17 34 48" src="https://github.com/deividfortuna/fipe/assets/66134406/cb4f9079-7905-4adf-920a-ffd74572e12f">


Segue contribuicao!!! quanto antes restaurar...melhor

**Comment by luizfelipedev-agillity** [comment]
esta de volta

**Comment by MarksEliel** [comment]
@deividfortuna poderia dar um feedback do que aconteceu? nós estamos dispostos a cooperar também, temos uma infraestrutura que pode comportar perfeitamente, ou podemos te passar contato de fornecedores com um melhor custo beneficio para que você possa hospedar a api, temos projetos rodando desde 2013 e compromisso em manter o seu serviço online se precisa fala comigo: wa.me/5584996463822

**Comment by deividfortuna** [comment]
consegui arrumar aqui provisoriamente, estarei vendo uma solução permanente em breve.

**Comment by deividfortuna** [comment]
@MarksEliel https://github.com/deividfortuna/fipe/issues/70#issuecomment-1460669924

**Comment by MarksEliel** [comment]
Sim, novamente fora, acabei desenvolvendo a minha própria API com um Crawler do site oficial da FIPE.
Quem tiver interesse me chama no whatsapp: wa.me/5584996463822

**Comment by marcelobm33** [comment]
OI, @deividfortuna, fiz uma doacao atraves o paypal, poderias verificar pq caiu o servidor?

**Comment by MarksEliel** [comment]
> OI, @deividfortuna, fiz uma doacao atraves o paypal, poderias verificar pq caiu o servidor?

Opa @marcelobm33 me chama no WhatsApp 84996463822

**Comment by deividfortuna** [comment]
@marcelobm33 muito obrigado pela doação, o servidor ja voltou ao normal ☺️
