### ISSUE TITLE
Só tem carros

### ISSUE THREAD

**Issue by luishenriqueturani** [deividfortuna/fipe#71]
Olhando aqui os resultados, notei que só tem carros, é isso mesmo?
Outra coisa, vem os resultados tendo o modelo e a versão dos veículos junto, se viesse separado seria melhor, é mais utilizado por otimizar os dados salvos, por exemplo:
Marca: Chevrolet
Modelo: Onix
versão: Joy

**Comment by deividfortuna** [comment]
E ai @luishenriqueturani,

Você pode usar `$marcas = FipeCaminhoes::getMarcas(); ` ou `$marcas = FipeCaminhoes::FipeMotos();`
Sim, o problema já foi corrigido na API mas a biblioteca ainda não foi atualizada, Você também pode usar a API diretamente:
https://deividfortuna.github.io/fipe/v2/

Abraço
