### ISSUE TITLE
Precisa de mais modelos flex

### ISSUE THREAD

**Issue by YuriSouzaDev** [deividfortuna/fipe#72]
Alguns carros que são flex, mas na listagem aparece apenas a gasolina

exemplo: siena 1.0 2010. Tenho a versão flex, mas na listagem aparece apenas a gasolina. Sendo que o preço difere um pouco quando o carro é flex

**Comment by deividfortuna** [comment]
@YuriSouzaDev os dados são da FIPE, se eles não incluem a API não vai retornar 😞
