### ISSUE TITLE
API FORA DO AR

### ISSUE THREAD

**Issue by marcelobm33** [deividfortuna/fipe#73]
@deividfortuna fiz uma contribuicao, poderias verificar pq o servidor esta fora do ar?

Você doou R$ 50,00 para deividfortuna@gmail.com | Você doou R$ 50,00 para deividfortuna@gmail.com
-- | --
Você doou R$ 50,00 para deividfortuna@gmail.com

Você doou R$ 50,00 para [deividfortuna@gmail.com](mailto:deividfortuna@gmail.com)
Obrigado por usar o PayPal.
Detalhes da doação
Data:	7 de outubro de 2023
ID da transação:	6KK60886MB139245A
Objetivo:	Agradecimento
Referência:	  AGRADECIMENTO_GITHUB_FIPE

**Comment by deividfortuna** [comment]
Muito obrigado pela doação @marcelobm33, o problema foi resolvido, servidor esta no ar novamente https://parallelum.com.br/status
