### ISSUE TITLE
Veiculos Eletricos

### ISSUE THREAD

**Issue by Gabrieldsm25** [deividfortuna/fipe#74]
Percebi que os veículos que são elétricos estão cadastrados como GASOLINA. Poderia fazer essa alteração para que eles retornem o 'Combustivel' correto. No nome deles esta como (ElÃ©trico)

![image](https://github.com/deividfortuna/fipe/assets/102314161/1f2dfcea-f1c2-42c4-8f44-72549fd98138)

**Comment by deividfortuna** [comment]
Opa @Gabrieldsm25  pode me mandar os dados de um veiculo como exemplo?

**Comment by LordMrcS** [comment]
> Opa @Gabrieldsm25 pode me mandar os dados de um veiculo como exemplo?

http://veiculos.fipe.org.br?carro/audi/5-2024/008274-0/2024/g/f4jqmhyfnbdt3

É na FIPE que parece que tá errado mesmo.
