### ISSUE TITLE
Rate limit exceeded (mesmo na versão paga)

### ISSUE THREAD

**Issue by cirofeitosa** [deividfortuna/fipe#84]
Hoje resolvemos fazer um teste com esta API e, mesmo utilizando a versão paga (Pro), foi interrompido com o erro:

```
{
"error":"rate limit exceeded. Please visit https://fipe.online to get a token"
}
```

Existe algum parâmetro adicional que precisa informar para não ocorrer isso?

**Comment by cirofeitosa** [comment]
O problema estava no código da nossa aplicação, onde o header estava sendo passado de forma errada.

**Comment by IngridASilva** [comment]
Olá @cirofeitosa, consegue me auxiliar? Estou com essa dificuldade, como passou o header corretamente?

**Comment by cirofeitosa** [comment]
> Olá [@cirofeitosa](https://github.com/cirofeitosa), consegue me auxiliar? Estou com essa dificuldade, como passou o header corretamente?

Qual linguagem está utilizando? 

Aqui o nosso erro foi exatamente no header, cada parâmetro deve ser informado com ":" na separação. 

Exemplo: 

```
Authorization: Bearer XYZ
```

Mas em termos gerais, o dono do projeto te responde rapidamente, se precisar.
