### ISSUE TITLE
Não consigo baixar o CSV no plano PRO

### ISSUE THREAD

**Issue by kevinzezel** [deividfortuna/fipe#86]
Boa tarde,

Acabei de fazer assinatura do plano PRO, porém não consigo fazer download na página de vocês.

Segue erro

<img width="1206" alt="Captura de Tela 2024-07-21 às 13 22 27" src="https://github.com/user-attachments/assets/733e9949-e276-4dea-85de-f9020bfab9bc">

**Comment by deividfortuna** [comment]
O download deve feito através do botão: https://fipe.online/dashboard/billing
