### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by bBenettiz** [deividfortuna/fipe#88]
Não consigo consumir os dados da api, fiz uma verificação da url, parece estar com algum problema, seria isso mesmo, ou é algum problema da minha aplicação?

**Comment by deividfortuna** [comment]
Vou precisar de mais informações para te ajudar. A API parece estar funcionando normal. Qual a url você esta fazendo o request?

**Comment by felipeArnold** [comment]
Eu também passo por isso diversas vezes, por exemplo nessa consulta FipeCarros::getAnos(43, 1786), isso acontece mais em ambiente de produção para mim, se rodo o mesmo em ambiente de desenvolvimento funciona de boa.

**Comment by deividfortuna** [comment]
Talvez o erro que você esteja recendo em produção esta relacionado com o limite no numero requisições para usuários não autenticados. Como mencionado aqui: https://github.com/deividfortuna/fipe/blob/master/README.md

**Comment by deividfortuna** [comment]
Oi @rgattermann, tens o body da resposta? todos os requestes passam por Cloudflare proxy....

**Comment by rgattermann** [comment]
Nos ultimos dias não tenho mais recebido erro 500. Mas agora tenho recebido status code 400 sem body de response. Posso colocar aqui o AxiosError completo. Mas já estava tratando com você por e-mail, ainda aguardo resposta por la.
