### ISSUE TITLE
Arquivo CSV com número reduzido de veículos

### ISSUE THREAD

**Issue by leandrogrison** [deividfortuna/fipe#89]
Ao baixar a tabela Fipe de Agosto/2024 pelo arquivo CSV, notei que ficou faltando muitos veículos, até de marcas conhecidas como da BYD. O arquivo CSV está 5x menor se comparado a versão do mês anterior.

Ocorreu algum problema de processamento referente a tabela do mês de Agosto/2024?

**Comment by deividfortuna** [comment]
Sim, teve um problema mas ja foi resolvido. Pode tentar novamente. Obrigado por reportar.
