### ISSUE TITLE
Tabela de Setembro está com menos veículos

### ISSUE THREAD

**Issue by leandrogrison** [deividfortuna/fipe#90]
Olá,

Ao abaixar a tabela Fipe de setembro/2024, o arquivo está com aproximadamente 6000 veículos a menos se comparado a Agosto/2024.

**Comment by leandrogrison** [comment]
Ao baixar hoje (03/09), veio a tabela completa, parece que nos primeiros dias vem apenas alguns veículos.

**Comment by deividfortuna** [comment]
Exato, obrigado por reportar @leandrogrison, estou trabalhando na correção

**Comment by nemoelguedes** [comment]
Bom dia, fiz a aquisição e continua com menos veículos.

**Comment by doliveiraweb** [comment]
Alguém conseguiu baixar a tabela completa? Aqui até agora nada.

**Comment by nemoelguedes** [comment]
> Exato, obrigado por reportar @leandrogrison, estou trabalhando na correção

Alguma novidade?

**Comment by deividfortuna** [comment]
Quantos linhas estão sendo retornadas?

**Comment by leandrogrison** [comment]
Baixei hoje novamente e parece normal: o arquivo tem 47.488 linhas.
